<?php
// $Id$

/**
 * @file
 * Provides a way to upgrade a recurring product.
 *
 * Initial module development sponsored by Marketing Results
 * http://www.marketing-results.com.au/
 *
 * Development
 *   Chris Hood http://univate.com.au
 */

/**
 * Implementation hook_menu()
 */
function uc_recurring_upgrade_menu() {
  $items['uc_recurring_upgrade/autocomplete'] = array(
    'type' => MENU_CALLBACK,
    'title' => 'Recurring Upgrade Autocomplete',
    'page callback' => 'uc_recurring_upgrade_autocomplete',
    'access arguments' => array('administer recurring fees'),
    'file' => 'uc_recurring_upgrade.inc'
  );
  $items['uc_recurring_upgrade/ahah/%'] = array(
    'type' => MENU_CALLBACK,
    'page callback' => uc_recurring_upgrade_ahah,
    'page arguments' => array(2),
    'access arguments' => array('administer recurring fees'),
    'file' => 'uc_recurring_upgrade.inc'
  );

  return $items;
}

/**
 * Implementation of hook_product_feature().
 */
function uc_recurring_upgrade_product_feature() {
  $features[] = array(
    'id' => 'recurring_upgrade',
    'title' => t('Upgrade recurring fee'),
    'callback' => 'uc_recurring_upgrade_feature_form',
    'delete' => 'uc_recurring_upgrade_feature_delete',
    'settings' => 'uc_recurring_upgrade_settings_form',
  );
  return $features;
}

/**
 *
 */
function uc_recurring_upgrade_feature_form($form_state, $node, $feature) {
  if (!empty($feature)) {
    $product = uc_recurring_upgrade_load($feature['pfid']);
  }
  $form['description'] = array(
    '#value' => t('This product feature allows you to upgrade a recurring fee. To implement you first need to select the product being upgraded from, if the user purchasing this product has the original recurring product selected on the left below then they will have their recurring fee for that order upgrade to the recurring fee selected below. You can upgrade also upgrade between two recurring options on the same product node (e.g. if you are using an attribute to specifying different recurring options weekly, monthly)'),
  );
  $form['product_from'] = array(
    '#type' => 'fieldset',
    '#title' => t('Only apply if...'),
    '#description' => t('Select the recurring product being upgraded from.'),
    '#attributes' => array('style' => 'width: 46%; float: left;')
  );
  $form['product_from']['product_from_id'] = array(
    '#type' => 'textfield',
    '#title' => t('Product ID'),
    '#description' => t('Enter product name or ID.'),
    '#size' => 20,
    '#autocomplete_path' => 'uc_recurring_upgrade/autocomplete',
    '#ahah' => array(
      'event' => 'change',
      'path' => 'uc_recurring_upgrade/ahah/product_model',
      'wrapper' => 'product-from-model',
      'method' => 'replace',
      'effect' => 'fade',
      'progress' => array(
      ),
    ),
  );
  $form['product_from']['product_from_model'] = array(
    '#value' => '<div id="product-from-model"></div>'
  );

  $form['product_to'] = array(
    '#type' => 'fieldset',
    '#title' => t('Upgrade Recurring fee to'),
    '#description' => t('Select which recurring fee to upgrade to.'),
    '#attributes' => array('style' => 'width: 46%; float: right;')
  );
  $features = uc_product_feature_load_multiple($node->nid);
  $recurring_options = array();
  foreach($features as $pfid => $feature) {
    if ($feature->fid == 'recurring') {
      $recurring_options[$pfid] = $feature->description;
    }
  }
  if (empty($recurring_options)) {
    $form['product_to']['add_recurring'] = array(
      '#value' => t('Need to first create a recurring product feature for this product'),
    );
  }
  else {
    $form['product_to']['upgrade_pfid'] = array(
      '#type' => 'radios',
      '#options' => $recurring_options,
    );
  }
  $form['recurring'] = array(
    '#type' => 'fieldset',
    '#title' => 'Recurring Settings',
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#attributes' => array('style' => 'clear: both;')
  );
  $form['recurring']['next_charge'] = array(
    '#type' => 'select',
    '#title' => 'Next renewal date',
    '#options' => array(
      'same' => t('Keep the next renewal date the same.'),
      'reset' => t('Reset the renewal date to upgraded date.'),
    ),
  );
  $form['recurring']['upgrade'] = array(
    '#type' => 'radios',
    '#title' => t('Upgrade calculation'),
    '#options' => uc_recurring_upgrade_calculations(),
    '#default_value' => 'prorata',
  );
  return uc_product_feature_form($form);
}

function uc_recurring_upgrade_feature_form_submit($form, &$form_state) {
  dsm($form_state);

}

/**
 *
 */
function uc_recurring_upgrade_feature_delete($pfid) {

}

/**
 *
 */
function uc_recurring_upgrade_settings_form() {
}


/**
 * Load recurring upgrade feature object from database.
 */
function uc_recurring_upgrade_load($pfid) {
  return db_fetch_object(db_query("SELECT * FROM {uc_recurring_upgrade_product} WHERE pfid = %d", $pfid));
}

/**
 * Implementation of hook_order().
 */
function uc_recurring_upgrade_order($op, &$arg1, $arg2) {
  
}

/**
 *
 */
function uc_recurring_upgrade_calculations() {
  $calc = array(
    'prorata' => t('<strong>Pro-rata</strong> - calcuate what is remaining on current plan and what is now due until the next renewal.'),
    'backpay' => t('<strong>Backpay</strong> - calculate what has been paid already on the customers current plan compared to the difference if they started on the new plan from the start, this difference is charged on upgrade.'),
  );
  drupal_alter('recurring_upgrade_calculation', $calc);
  return $calc;
}
